/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saúde da API */
        get: operations["saude_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saude/dados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validação do dataset carregado
         * @description Confere as contagens das 11 tabelas contra o esperado. Um banco parcialmente carregado é pior que vazio: as telas funcionam, mas os números estão errados.
         */
        get: operations["saude_dados_saude_dados_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar pacientes
         * @description Lista paginada com filtros combináveis. Exclui por padrão os 2 pacientes com ano de nascimento implausível, retornando 1.128 de 1.130.
         *
         *     Não há busca por nome: o OMOP CDM é desidentificado e a tabela de pessoa não tem esse campo (ADR-009).
         */
        get: operations["listar_pacientes_pacientes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do paciente */
        get: operations["obter_paciente_pacientes__id_pessoa__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline clínica unificada
         * @description Condições, medicamentos, procedimentos e exames numa linha do tempo ordenada por data.
         *
         *     Os eventos de exame vêm com `valor_disponivel: false` — o dataset não traz resultados (ADR-008). Medicamentos já filtrados.
         */
        get: operations["obter_timeline_pacientes__id_pessoa__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/condicoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Condições do paciente */
        get: operations["listar_condicoes_pacientes__id_pessoa__condicoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/medicamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Medicamentos do paciente
         * @description Apenas medicamentos RxNorm válidos. A resposta declara quantos registros foram excluídos por trazerem código de condição (ADR-008).
         */
        get: operations["listar_medicamentos_pacientes__id_pessoa__medicamentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/procedimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Procedimentos do paciente */
        get: operations["listar_procedimentos_pacientes__id_pessoa__procedimentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/exames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exames do paciente
         * @description Exames pedidos. **O dataset não traz resultados**: `valor_numerico` é sempre nulo. A UI deve exibir 'não disponível', nunca vazio (ADR-008).
         */
        get: operations["listar_exames_pacientes__id_pessoa__exames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumo clínico em texto
         * @description Resumo do prontuário em português, gerado por **template determinístico** — a mesma entrada produz sempre a mesma saída, sem inferência de modelo.
         *
         *     O texto declara explicitamente que os exames não têm resultados disponíveis: omitir isso levaria quem lê a concluir ausência de alteração (ADR-008).
         */
        get: operations["obter_resumo_pacientes__id_pessoa__resumo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/alergias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alergias do paciente
         * @description Lista vazia quando não há alergia registrada — não é erro.
         */
        get: operations["listar_alergias_pacientes__id_pessoa__alergias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atendimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar atendimentos
         * @description Lista paginada com filtros. A base cobre **1909 a janeiro de 2019** — um filtro de data baseado em recência retornaria vazio.
         */
        get: operations["listar_atendimentos_atendimentos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atendimentos/{id_atendimento}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhe do atendimento
         * @description O atendimento e tudo que aconteceu nele. Seções vazias vêm como lista vazia, não omitidas.
         *
         *     Um atendimento chega a 97 exames: a UI deve colapsar seções longas.
         */
        get: operations["obter_atendimento_atendimentos__id_atendimento__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pacientes/{id_pessoa}/trajetoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trajetória de atendimentos
         * @description Sequência de atendimentos seguindo `id_atendimento_anterior` — 31.027 atendimentos têm predecessor.
         *
         *     Paciente sem encadeamento recebe os atendimentos em ordem cronológica. A resposta sinaliza truncamento e detecção de ciclo: nada no dataset garante que a cadeia seja acíclica.
         */
        get: operations["obter_trajetoria_pacientes__id_pessoa__trajetoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estatisticas/reinternacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pacientes com internações repetidas
         * @description Os 78 pacientes com mais de uma internação no histórico.
         *
         *     **Atenção:** isto é simplesmente mais de uma internação registrada — **não** é a definição clínica de readmissão em 30 dias, e não deve ser lido como indicador de qualidade assistencial.
         */
        get: operations["listar_reinternacoes_estatisticas_reinternacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estatisticas/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumo populacional
         * @description Números-chave da base numa chamada.
         *
         *     **Não há estatística de valor de exame** — o dataset não traz resultados (ADR-008).
         */
        get: operations["obter_resumo_estatisticas_resumo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estatisticas/{dominio}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prevalência por domínio
         * @description Distingue **ocorrências** de **pacientes afetados** — confundir os dois é o erro mais fácil aqui. Exemplo: 'Infecção viral das vias aéreas superiores' tem 1.134 ocorrências em 711 pacientes; a prevalência é sobre os 711.
         *
         *     Domínios: `condicoes` (134), `medicamentos` (145 válidos), `procedimentos` (91), `exames` (240 — sem resultados).
         */
        get: operations["obter_prevalencia_estatisticas__dominio__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coortes/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prévia da coorte (só a contagem)
         * @description Para feedback ao vivo enquanto o usuário monta os critérios.
         */
        post: operations["previa_coorte_coortes_previa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coortes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Montar coorte
         * @description Combina critérios e devolve os pacientes. A resposta declara **todos** os filtros aplicados, inclusive os de qualidade (ADR-008).
         *
         *     Combinação sem resultado retorna `total: 0` — não é erro. Critério com nome inexistente retorna 400, para não parecer coorte vazia.
         */
        post: operations["criar_coorte_coortes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coortes/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exportar coorte em CSV
         * @description CSV com os critérios no cabeçalho. Limite de 1000 linhas.
         *
         *     Inclui o UUID além do `id_pessoa`: o ID é sequencial e específico desta carga, enquanto o UUID é o identificador estável para cruzar com outra fonte (ADR-009).
         */
        post: operations["exportar_coorte_coortes_exportar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dicionario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dicionário de conceitos clínicos
         * @description Os 535 códigos usados no dataset: SNOMED CT (272), RxNorm (146) e LOINC (117).
         *
         *     **As traduções não têm fonte auditável**: foram feitas a partir dos códigos, sem o vocabulário oficial do OHDSI. Para uso clínico, valide contra o Athena (ADR-001).
         *
         *     134 códigos trazem `observacao` preenchida, marcando o bug de ETL.
         */
        get: operations["listar_dicionario_dicionario_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dicionario/sugestoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autocomplete de nome clínico
         * @description Até 10 sugestões, as mais frequentes primeiro.
         */
        get: operations["obter_sugestoes_dicionario_sugestoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dicionario/{codigo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conceito por código */
        get: operations["obter_conceito_dicionario__codigo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/busca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar termo clínico em português
         * @description Busca nos nomes clínicos de todos os domínios, **ignorando acento e caixa**: 'pre-diabetes' acha 'Pré-diabetes'.
         *
         *     O banco usa locale C, então a normalização vem do `unaccent` (ADR-002).
         */
        get: operations["buscar_busca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AtendimentoDetalhe
         * @description Tudo que aconteceu no atendimento.
         */
        AtendimentoDetalhe: {
            /** Id Atendimento */
            id_atendimento: number;
            /** Id Pessoa */
            id_pessoa: number;
            /**
             * Tipo
             * @description Ambulatorial, Emergência ou Internação
             */
            tipo?: string | null;
            /** Data Inicio */
            data_inicio: string | null;
            /** Data Fim */
            data_fim: string | null;
            /**
             * Duracao Dias
             * @description Dias entre início e fim
             */
            duracao_dias?: number | null;
            /** Sexo */
            sexo?: string | null;
            /** Idade */
            idade?: number | null;
            /** Id Atendimento Anterior */
            id_atendimento_anterior?: number | null;
            /** Condicoes */
            condicoes: components["schemas"]["ItemCondicao"][];
            /**
             * Medicamentos
             * @description Apenas medicamentos RxNorm válidos (ADR-008)
             */
            medicamentos: components["schemas"]["ItemMedicamento"][];
            /** Procedimentos */
            procedimentos: components["schemas"]["ItemProcedimento"][];
            /**
             * Exames
             * @description Exames pedidos — o dataset não traz resultados (ADR-008)
             */
            exames: components["schemas"]["ItemExame"][];
        };
        /** AtendimentoResumo */
        AtendimentoResumo: {
            /** Id Atendimento */
            id_atendimento: number;
            /** Id Pessoa */
            id_pessoa: number;
            /**
             * Tipo
             * @description Ambulatorial, Emergência ou Internação
             */
            tipo?: string | null;
            /** Data Inicio */
            data_inicio: string | null;
            /** Data Fim */
            data_fim: string | null;
            /**
             * Duracao Dias
             * @description Dias entre início e fim
             */
            duracao_dias?: number | null;
        };
        /** ContadoresPaciente */
        ContadoresPaciente: {
            /** Condicoes */
            condicoes: number;
            /**
             * Medicamentos
             * @description Apenas medicamentos RxNorm válidos; os inconsistentes são excluídos (ADR-008)
             */
            medicamentos: number;
            /** Procedimentos */
            procedimentos: number;
            /**
             * Exames
             * @description Exames pedidos — sem resultados disponíveis
             */
            exames: number;
            /** Atendimentos */
            atendimentos: number;
            /** Alergias */
            alergias: number;
        };
        /** ContagemRotulada */
        ContagemRotulada: {
            /** Rotulo */
            rotulo: string;
            /** Pacientes */
            pacientes: number;
        };
        /** ContagemTabela */
        ContagemTabela: {
            /** Tabela */
            tabela: string;
            /** Linhas */
            linhas: number;
            /** Esperado */
            esperado: number;
            /** Conforme */
            conforme: boolean;
        };
        /**
         * CriteriosCoorte
         * @description Critérios combináveis. Compostos via ORM, sem concatenação (ADR-006).
         */
        CriteriosCoorte: {
            /** Condicoes */
            condicoes?: string[];
            /**
             * Condicoes Todas
             * @description Falso: paciente com QUALQUER condição da lista. Verdadeiro: paciente com TODAS elas.
             * @default false
             */
            condicoes_todas: boolean;
            /** Medicamentos */
            medicamentos?: string[];
            /** Sexo */
            sexo?: string | null;
            /** Raca */
            raca?: string | null;
            /** Idade Min */
            idade_min?: number | null;
            /** Idade Max */
            idade_max?: number | null;
            /** Tipo Atendimento */
            tipo_atendimento?: string | null;
        };
        /**
         * EventoTimeline
         * @description Evento na linha do tempo unificada (HU-1.3).
         */
        EventoTimeline: {
            /**
             * Tipo
             * @description condicao | medicamento | procedimento | exame
             */
            tipo: string;
            /** Data */
            data: string | null;
            /** Nome */
            nome: string | null;
            /** Id Atendimento */
            id_atendimento: number | null;
            /** Codigo Origem */
            codigo_origem: string | null;
            /**
             * Pk
             * @description Identificador do registro de origem
             */
            pk: number;
            /**
             * Valor Disponivel
             * @description Falso nos exames: o dataset não traz resultados (ADR-008)
             * @default true
             */
            valor_disponivel: boolean;
        };
        /** FaixaEtaria */
        FaixaEtaria: {
            /** Faixa */
            faixa: string;
            /** Pacientes */
            pacientes: number;
        };
        /**
         * FiltroQualidade
         * @description Filtros de qualidade aplicados a uma resposta (ADR-008).
         *
         *     A API declara o que foi filtrado para que a UI possa mostrá-lo, em vez de
         *     esconder a limitação do dataset.
         */
        FiltroQualidade: {
            /** Descricao */
            descricao: string;
            /**
             * Registros Excluidos
             * @default 0
             */
            registros_excluidos: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemAlergia */
        ItemAlergia: {
            /** Pk */
            pk: number;
            /** Nome Observacao */
            nome_observacao: string | null;
            /** Data */
            data: string | null;
        };
        /** ItemCondicao */
        ItemCondicao: {
            /** Id Condicao */
            id_condicao: number;
            /** Nome Condicao */
            nome_condicao: string | null;
            /** Data Inicio */
            data_inicio: string | null;
            /** Data Fim */
            data_fim: string | null;
            /** Id Atendimento */
            id_atendimento: number | null;
            /** Codigo Origem Condicao */
            codigo_origem_condicao: string | null;
        };
        /** ItemDicionario */
        ItemDicionario: {
            /** Codigo Origem */
            codigo_origem: string;
            /** Vocabulario */
            vocabulario: string | null;
            /** Nome Portugues */
            nome_portugues: string | null;
            /** Dominios */
            dominios: string | null;
            /** Ocorrencias */
            ocorrencias: number | null;
            /**
             * Observacao
             * @description Preenchido nos códigos afetados por bug de ETL
             */
            observacao?: string | null;
        };
        /**
         * ItemExame
         * @description Exame pedido. O dataset não traz resultados (ADR-008).
         */
        ItemExame: {
            /** Pk */
            pk: number;
            /** Nome Exame */
            nome_exame: string | null;
            /** Data */
            data: string | null;
            /** Id Atendimento */
            id_atendimento: number | null;
            /** Codigo Origem Exame */
            codigo_origem_exame: string | null;
            /**
             * Valor Numerico
             * @description Sempre nulo: os resultados se perderam no ETL do Synthea. A UI deve exibir 'não disponível', nunca vazio (ADR-008).
             */
            valor_numerico?: null;
        };
        /** ItemMedicamento */
        ItemMedicamento: {
            /** Pk */
            pk: number;
            /** Nome Medicamento */
            nome_medicamento: string | null;
            /** Data Inicio */
            data_inicio: string | null;
            /** Data Fim */
            data_fim: string | null;
            /** Dias Fornecimento */
            dias_fornecimento: number | null;
            /** Id Atendimento */
            id_atendimento: number | null;
            /** Codigo Origem Medicamento */
            codigo_origem_medicamento: string | null;
        };
        /** ItemPrevalencia */
        ItemPrevalencia: {
            /** Nome */
            nome: string;
            /**
             * Ocorrencias
             * @description Total de registros
             */
            ocorrencias: number;
            /**
             * Pacientes
             * @description Pacientes distintos afetados — é esta a base da prevalência
             */
            pacientes: number;
            /** Percentual Pacientes */
            percentual_pacientes: number;
        };
        /** ItemProcedimento */
        ItemProcedimento: {
            /** Id Procedimento */
            id_procedimento: number;
            /** Nome Procedimento */
            nome_procedimento: string | null;
            /** Data */
            data: string | null;
            /** Id Atendimento */
            id_atendimento: number | null;
            /** Codigo Origem Procedimento */
            codigo_origem_procedimento: string | null;
        };
        /** ItemReinternacao */
        ItemReinternacao: {
            /** Id Pessoa */
            id_pessoa: number;
            /** Sexo */
            sexo: string | null;
            /** Idade */
            idade: number | null;
            /** Internacoes */
            internacoes: number;
            /** Menor Intervalo Dias */
            menor_intervalo_dias: number | null;
            /** Maior Intervalo Dias */
            maior_intervalo_dias: number | null;
        };
        /** JanelaObservacao */
        JanelaObservacao: {
            /** Data Inicio */
            data_inicio: string | null;
            /** Data Fim */
            data_fim: string | null;
        };
        /**
         * ListaMedicamentos
         * @description Lista de medicamentos com o filtro de qualidade declarado (ADR-008).
         */
        ListaMedicamentos: {
            /** Itens */
            itens: components["schemas"]["ItemMedicamento"][];
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
            filtro_qualidade: components["schemas"]["FiltroQualidade"];
        };
        /** ListaPrevalencia */
        ListaPrevalencia: {
            /** Itens */
            itens: components["schemas"]["ItemPrevalencia"][];
            /** Total */
            total: number;
            /**
             * Denominador
             * @description Pacientes considerados no cálculo
             */
            denominador: number;
            filtro_qualidade?: components["schemas"]["FiltroQualidade"] | null;
        };
        /** PacienteDetalhe */
        PacienteDetalhe: {
            /** Id Pessoa */
            id_pessoa: number;
            /**
             * Codigo Origem Pessoa
             * @description UUID do Synthea — identificador estável entre cargas
             */
            codigo_origem_pessoa?: string | null;
            /** Sexo */
            sexo: string | null;
            /**
             * Idade
             * @description Calculada sobre a data atual
             */
            idade?: number | null;
            /** Raca */
            raca: string | null;
            /** Etnia */
            etnia: string | null;
            /** Ano Nascimento */
            ano_nascimento: number | null;
            /** Sexo Descricao */
            sexo_descricao: string | null;
            /** Raca Descricao */
            raca_descricao: string | null;
            janela_observacao?: components["schemas"]["JanelaObservacao"] | null;
            contadores: components["schemas"]["ContadoresPaciente"];
            /**
             * Aviso
             * @description Preenchido quando o ano de nascimento é implausível
             */
            aviso?: string | null;
        };
        /**
         * PacienteResumo
         * @description Item de lista. Pacientes não têm nome (ADR-009).
         */
        PacienteResumo: {
            /** Id Pessoa */
            id_pessoa: number;
            /**
             * Codigo Origem Pessoa
             * @description UUID do Synthea — identificador estável entre cargas
             */
            codigo_origem_pessoa?: string | null;
            /** Sexo */
            sexo: string | null;
            /**
             * Idade
             * @description Calculada sobre a data atual
             */
            idade?: number | null;
            /** Raca */
            raca: string | null;
            /** Etnia */
            etnia: string | null;
        };
        /** Pagina[AtendimentoResumo] */
        Pagina_AtendimentoResumo_: {
            /** Itens */
            itens: components["schemas"]["AtendimentoResumo"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[EventoTimeline] */
        Pagina_EventoTimeline_: {
            /** Itens */
            itens: components["schemas"]["EventoTimeline"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[ItemCondicao] */
        Pagina_ItemCondicao_: {
            /** Itens */
            itens: components["schemas"]["ItemCondicao"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[ItemDicionario] */
        Pagina_ItemDicionario_: {
            /** Itens */
            itens: components["schemas"]["ItemDicionario"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[ItemExame] */
        Pagina_ItemExame_: {
            /** Itens */
            itens: components["schemas"]["ItemExame"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[ItemProcedimento] */
        Pagina_ItemProcedimento_: {
            /** Itens */
            itens: components["schemas"]["ItemProcedimento"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[ItemReinternacao] */
        Pagina_ItemReinternacao_: {
            /** Itens */
            itens: components["schemas"]["ItemReinternacao"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /** Pagina[PacienteResumo] */
        Pagina_PacienteResumo_: {
            /** Itens */
            itens: components["schemas"]["PacienteResumo"][];
            /**
             * Total
             * @description Total de registros que atendem aos filtros
             */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
        };
        /**
         * PassoTrajetoria
         * @description Um atendimento na sequência encadeada.
         */
        PassoTrajetoria: {
            /** Ordem */
            ordem: number;
            /** Id Atendimento */
            id_atendimento: number;
            /** Tipo */
            tipo: string | null;
            /** Data Inicio */
            data_inicio: string | null;
            /** Dias Desde Anterior */
            dias_desde_anterior: number | null;
            /** Condicoes */
            condicoes: string[];
        };
        /** PreviaCoorte */
        PreviaCoorte: {
            /** Total */
            total: number;
            /** Filtros Aplicados */
            filtros_aplicados: string[];
        };
        /** ResultadoBusca */
        ResultadoBusca: {
            /** Termo */
            termo: string;
            /** Condicoes */
            condicoes: string[];
            /** Medicamentos */
            medicamentos: string[];
            /** Procedimentos */
            procedimentos: string[];
            /** Exames */
            exames: string[];
            /** Observacoes */
            observacoes: string[];
            /**
             * Truncado
             * @description Verdadeiro se algum domínio atingiu o limite
             * @default false
             */
            truncado: boolean;
        };
        /** ResultadoCoorte */
        ResultadoCoorte: {
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
            /** Itens */
            itens: components["schemas"]["PacienteResumo"][];
            /**
             * Filtros Aplicados
             * @description Inclui os filtros de qualidade, não só os critérios pedidos
             */
            filtros_aplicados: string[];
        };
        /** ResumoPopulacional */
        ResumoPopulacional: {
            /**
             * Total Pacientes
             * @description Exclui os 2 nascimentos implausíveis
             */
            total_pacientes: number;
            /** Por Sexo */
            por_sexo: components["schemas"]["ContagemRotulada"][];
            /** Por Raca */
            por_raca: components["schemas"]["ContagemRotulada"][];
            /** Piramide Etaria */
            piramide_etaria: components["schemas"]["FaixaEtaria"][];
            /** Atendimentos Por Tipo */
            atendimentos_por_tipo: components["schemas"]["ContagemRotulada"][];
            /**
             * Pacientes Multimorbidade
             * @description Pacientes com 2 ou mais condições crônicas distintas
             */
            pacientes_multimorbidade: number;
            /** Janela Temporal */
            janela_temporal: string;
            /** Aviso Representatividade */
            aviso_representatividade: string;
        };
        /** StatusDados */
        StatusDados: {
            /** Carregado */
            carregado: boolean;
            /** Conforme */
            conforme: boolean;
            /** Resumo */
            resumo: string;
            /** Tabelas */
            tabelas: components["schemas"]["ContagemTabela"][];
        };
        /** StatusSaude */
        StatusSaude: {
            /** Status */
            status: string;
            /** Banco Conectado */
            banco_conectado: boolean;
            /** Detalhe */
            detalhe?: string | null;
        };
        /** Sugestao */
        Sugestao: {
            /** Nome */
            nome: string;
            /** Ocorrencias */
            ocorrencias: number;
        };
        /** Trajetoria */
        Trajetoria: {
            /** Id Pessoa */
            id_pessoa: number;
            /** Total Atendimentos */
            total_atendimentos: number;
            /** Passos */
            passos: components["schemas"]["PassoTrajetoria"][];
            /**
             * Truncada
             * @description Verdadeiro se o limite de passos foi atingido
             * @default false
             */
            truncada: boolean;
            /**
             * Ciclo Detectado
             * @description Verdadeiro se a cadeia revisita um atendimento — nada no dataset garante ausência de ciclo
             * @default false
             */
            ciclo_detectado: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saude_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusSaude"];
                };
            };
        };
    };
    saude_dados_saude_dados_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusDados"];
                };
            };
        };
    };
    listar_pacientes_pacientes_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                sexo?: ("M" | "F") | null;
                /** @description branca, preta, amarela… */
                raca?: string | null;
                etnia?: string | null;
                idade_min?: number | null;
                idade_max?: number | null;
                /** @description Nome clínico exato, em português */
                condicao?: string | null;
                ordenar_por?: "id_pessoa" | "idade";
                decrescente?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_PacienteResumo_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_paciente_pacientes__id_pessoa__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_timeline_pacientes__id_pessoa__timeline_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                /** @description Repita o parâmetro para múltiplos tipos */
                tipo?: ("condicao" | "medicamento" | "procedimento" | "exame")[] | null;
                data_de?: string | null;
                data_ate?: string | null;
            };
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_EventoTimeline_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_condicoes_pacientes__id_pessoa__condicoes_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ItemCondicao_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_medicamentos_pacientes__id_pessoa__medicamentos_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaMedicamentos"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_procedimentos_pacientes__id_pessoa__procedimentos_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ItemProcedimento_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_exames_pacientes__id_pessoa__exames_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ItemExame_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_resumo_pacientes__id_pessoa__resumo_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_alergias_pacientes__id_pessoa__alergias_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador do paciente */
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemAlergia"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_atendimentos_atendimentos_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                tipo?: ("Ambulatorial" | "Emergência" | "Internação") | null;
                id_pessoa?: number | null;
                data_de?: string | null;
                data_ate?: string | null;
                /** @description Mais recentes primeiro */
                decrescente?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_AtendimentoResumo_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_atendimento_atendimentos__id_atendimento__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_atendimento: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtendimentoDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_trajetoria_pacientes__id_pessoa__trajetoria_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id_pessoa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trajetoria"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_reinternacoes_estatisticas_reinternacoes_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                /** @description Só pacientes cujo menor intervalo é <= este valor */
                janela_dias?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ItemReinternacao_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_resumo_estatisticas_resumo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumoPopulacional"];
                };
            };
        };
    };
    obter_prevalencia_estatisticas__dominio__get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                sexo?: ("M" | "F") | null;
                raca?: string | null;
                idade_min?: number | null;
                idade_max?: number | null;
                ordenar_por?: "pacientes" | "ocorrencias" | "nome";
            };
            header?: never;
            path: {
                dominio: "condicoes" | "medicamentos" | "procedimentos" | "exames";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaPrevalencia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previa_coorte_coortes_previa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriosCoorte"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviaCoorte"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_coorte_coortes_post: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriosCoorte"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoCoorte"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_coorte_coortes_exportar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriteriosCoorte"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_dicionario_dicionario_get: {
        parameters: {
            query?: {
                pagina?: number;
                por_pagina?: number;
                vocabulario?: ("SNOMED CT" | "RxNorm" | "LOINC") | null;
                /** @description condição, exame… */
                dominio?: string | null;
                /** @description Busca no nome ou no código */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ItemDicionario_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_sugestoes_dicionario_sugestoes_get: {
        parameters: {
            query: {
                q: string;
                dominio?: "condicoes" | "medicamentos" | "procedimentos" | "exames" | "observacoes";
                limite?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sugestao"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_conceito_dicionario__codigo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Código SNOMED, RxNorm ou LOINC */
                codigo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDicionario"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_busca_get: {
        parameters: {
            query: {
                /** @description Mínimo 2 caracteres */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoBusca"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
